# -*- coding: utf-8 -*-
"""Project_d.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kdmRpCCaNqcfMKnxOZijuJgH6y-7jidd
"""

# For full Project Mail me for vatshayan007@gmail.com 

#Hi

def generateKey(string, key): 
	key = list(key) 
	if len(string) == len(key): 
		return(key) 
	else: 
		for i in range(len(string) -
					len(key)): 
			key.append(key[i % len(key)]) 
	return("" . join(key))

# This is Only 10% code, for Full code mail me Now. 
# Mail me Now (vatshayan007@gmail.com) for full Code  !

